version: '2'
services:
    perudoonline-app:
        image: perudoonline
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://perudoonline-postgresql:5432/PerudoOnline
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    perudoonline-postgresql:
        extends:
            file: postgresql.yml
            service: perudoonline-postgresql
